### ISSUE TITLE
create google analytics accounts for projects

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/analytics#4]
We need the accounts for: 
- [x] FaceBase
- [x] rbk
- [x] gpcr

We can set data sharing to allow access to anaytics data to external users..

**Comment by crisaless** [comment]
I need the URLs for synapse and cirm.

**Comment by crisaless** [comment]
Per Carl we'll just start with FaceBase, RBK and GPCR. I've created the accounts and added @hongsudt  - @RFSH and @carlkesselman as users

**Comment by hongsudt** [comment]
@crisaless can you share: 
* facebase with @robes, @bugacov, @carlkesselman  
* rbk with @robes, @svoinea, @carlkesselman 
* gpcr with @bugacov, @akumar03, @carlkesselman   
Thanks,

**Comment by crisaless** [comment]
There are some new folks (as far as inviting to google) so I'm asking them for their preferred google-related email.

**Comment by hongsudt** [comment]
@crisaless can we close this issue?

**Comment by hongsudt** [comment]
I am closing this issue now.
